name: coran-nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - nltk
  - fasttext  # El modelo que nos dijo el profesor (si no funciona probar con fasttext-wheel)
  - plotly
  - umap-learn
  - hdbscan
  - pip:
      - sentence-transformers
      - arabic-reshaper
      - python-bidi
      - camel_tools
      - scikit-learn
      - threadpoolctl
      - umap-learn
      - altair
      - googletrans
      - bertopic
